title: Ankush Jain
theme: minima
author: Ankush
email: ankush111215cse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 My wife is too looking too sexy today. She wears a revealing top and we had a good session in the morning.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
